const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#4A90E2",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#f7f7f8",
    cardForeground: "#0a0a0a",
    primary: "#4A90E2",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f0",
    mutedForeground: "#8e8ea0",
    accent: "#e8f0fc",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
    userBubble: "#4A90E2",
    userBubbleText: "#ffffff",
    aiBubble: "#f0f0f0",
    aiBubbleText: "#0a0a0a",
    surface: "#ffffff",
    geminiBlue: "#4285F4",
    geminiRed: "#EA4335",
    geminiYellow: "#FBBC04",
    geminiGreen: "#34A853",
  },
  dark: {
    text: "#ececf1",
    tint: "#4A90E2",
    background: "#212121",
    foreground: "#ececf1",
    card: "#2f2f2f",
    cardForeground: "#ececf1",
    primary: "#4A90E2",
    primaryForeground: "#ffffff",
    secondary: "#3a3a3a",
    secondaryForeground: "#ececf1",
    muted: "#3a3a3a",
    mutedForeground: "#8e8ea0",
    accent: "#2a3a5c",
    accentForeground: "#ececf1",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#3a3a3a",
    input: "#3a3a3a",
    userBubble: "#4A90E2",
    userBubbleText: "#ffffff",
    aiBubble: "#2f2f2f",
    aiBubbleText: "#ececf1",
    surface: "#2f2f2f",
    geminiBlue: "#4285F4",
    geminiRed: "#EA4335",
    geminiYellow: "#FBBC04",
    geminiGreen: "#34A853",
  },
  radius: 24,
};

export default colors;
